#!/bin/bash
instanceids=`aws ssm describe-instance-information --output text --query "InstanceInformationList[*]" | awk '{print $4}'`
for x in $instanceids
do
aws ssm send-command --document-name "AWS-RunShellScript" --instance-ids "$x" --parameters '{"commands":["sudo supervisorctl restart all"],"executionTimeout":["10"]}' --comment "sudo supervisorctl restart all" --timeout-seconds 60 --region ap-south-1
sleep 10;
done
